### ISSUE TITLE
Example is asking for a 'signer'

### ISSUE THREAD

**Issue by Subfortytwo** [skip-mev/skip-router-sdk#61]
Hello,

When I try to send with the route function, I am getting the following error:

```
Error: Unable to get Cosmos signer. Please provide a signer or a function to get a signer
    at SkipRouter.<anonymous> (/home/user/skiprouter/node_modules/@skip-router/core/src/client.ts:299:13)
    at Generator.next (<anonymous>)
    at /home/user/skiprouter/node_modules/@skip-router/core/dist/cjs/client.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/user/skiprouter/node_modules/@skip-router/core/dist/cjs/client.js:4:12)
    at SkipRouter.executeRoute (/home/user/skiprouter/node_modules/@skip-router/core/dist/cjs/client.js:85:16)
    at main (/home/user/skiprouter/index.ts:44:16)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

I declared it as:

```
  const client = new SkipRouter({
    apiURL: SKIP_API_URL,
    // @ts-expect-error
    getOfflineSigner: async (chainID) => {
      return DirectSecp256k1HdWallet.fromMnemonic(MNEMONIC);
    },
  });

```

Do you have any idea why it's not taking the signer?

Thank you very much

**Comment by Subfortytwo** [comment]
In` client.ts`

```
  async executeRoute(options: ExecuteRouteOptions) {
    const { route, userAddresses, validateGasBalance } = options;

    let getOfflineSigner = this.getCosmosSigner;
    if (options.getCosmosSigner) {
      getOfflineSigner = options.getCosmosSigner;
    }

    if (!getOfflineSigner) {
      throw new Error(
        "Unable to get Cosmos signer. Please provide a signer or a function to get a signer",
      );
    }
```

So we should declare it as getCosmosSigner:

```
  const client = new SkipRouter({
    apiURL: SKIP_API_URL,
    // @ts-expect-error
    getCosmosSigner: async (chainID) => {
      return DirectSecp256k1HdWallet.fromMnemonic(MNEMONIC);
    },
  });

```
